/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AboutContent {
  'bandMembers' : Array<string>,
  'biography' : string,
  'pressKit' : [] | [ExternalBlob],
  'photos' : Array<ExternalBlob>,
}
export interface AudioFile {
  'id' : string,
  'title' : string,
  'duration' : bigint,
  'file' : ExternalBlob,
  'trackNumber' : bigint,
}
export interface BookingConfig {
  'files' : Array<BookingFile>,
  'email' : string,
  'links' : Array<BookingLink>,
  'callToAction' : string,
}
export interface BookingFile {
  'id' : string,
  'file' : ExternalBlob,
  'name' : string,
  'fileType' : string,
}
export interface BookingLink {
  'id' : string,
  'url' : string,
  'linkLabel' : string,
  'type' : string,
}
export interface ButtonStyle {
  'backgroundColor' : string,
  'borderRadius' : bigint,
  'hoverBackgroundColor' : string,
  'borderStyle' : string,
  'size' : bigint,
  'borderWidth' : bigint,
  'shape' : string,
  'hoverTextColor' : string,
  'hoverBorderColor' : string,
  'borderColor' : string,
  'textColor' : string,
}
export interface CalendarEvent {
  'id' : string,
  'title' : string,
  'date' : Time,
  'description' : string,
  'location' : string,
}
export interface CanisterStatus {
  'moduleHash' : [] | [Uint8Array],
  'lastTopUpTime' : [] | [Time],
  'cycles' : bigint,
  'memorySize' : bigint,
  'canisterId' : string,
  'lastMaintenanceCheck' : Time,
}
export interface ContactConfig {
  'headline' : string,
  'email' : string,
  'socialMediaLinks' : Array<SocialMediaLink>,
}
export interface ContactMessage {
  'id' : string,
  'subject' : string,
  'name' : string,
  'read' : boolean,
  'email' : string,
  'message' : string,
  'timestamp' : Time,
}
export interface DesignConfig {
  'tagline' : string,
  'logo' : [] | [ExternalBlob],
  'heroMediaType' : HeroMediaType,
  'heroSubtitle' : string,
  'accentColor' : string,
  'logoSize' : bigint,
  'heroImage' : [] | [ExternalBlob],
  'logoVisibility' : LogoVisibility,
  'heroTextColor' : string,
  'heroTextSize' : bigint,
  'buttonStyle' : ButtonStyle,
  'quickButtons' : Array<QuickButton>,
  'heroVideo' : [] | [HeroVideo],
  'hoverOutlineColor' : string,
}
export type ExternalBlob = Uint8Array;
export interface FileItem {
  'id' : string,
  'file' : ExternalBlob,
  'name' : string,
  'folder' : string,
}
export type HeroMediaType = { 'video' : null } |
  { 'image' : null };
export interface HeroVideo {
  'muted' : boolean,
  'autoplay' : boolean,
  'file' : [] | [ExternalBlob],
  'externalUrl' : [] | [string],
  'shouldLoop' : boolean,
}
export interface HomepageConfig {
  'autoUpcomingShows' : boolean,
  'latestReleaseId' : [] | [string],
  'upcomingShowIds' : Array<string>,
  'featuredProductIds' : Array<string>,
}
export interface ImageFile {
  'id' : string,
  'file' : ExternalBlob,
  'isCover' : boolean,
}
export interface LegalContent {
  'privacyPolicy' : string,
  'lastUpdated' : Time,
  'imprint' : string,
  'termsOfService' : string,
}
export interface LogoVisibility { 'hero' : boolean, 'header' : boolean }
export interface MediaItem {
  'id' : string,
  'title' : string,
  'createdAt' : Time,
  'description' : string,
  'streamingPlatforms' : Array<StreamingPlatform>,
  'audioFiles' : Array<AudioFile>,
  'mediaType' : MediaType,
  'price' : bigint,
  'youtubeUrl' : [] | [string],
  'images' : Array<ImageFile>,
}
export type MediaType = { 'album' : null } |
  { 'video' : null } |
  { 'youtube' : null } |
  { 'single' : null };
export interface Message {
  'id' : string,
  'content' : string,
  'sender' : string,
  'timestamp' : Time,
  'threadId' : string,
}
export interface Product {
  'id' : string,
  'categories' : Array<string>,
  'order' : bigint,
  'name' : string,
  'createdAt' : Time,
  'description' : string,
  'variants' : Array<ProductVariant>,
  'isDigital' : boolean,
  'images' : Array<ExternalBlob>,
}
export interface ProductVariant {
  'id' : string,
  'name' : string,
  'stock' : bigint,
  'price' : bigint,
}
export interface QuickButton {
  'id' : string,
  'url' : string,
  'order' : bigint,
  'icon' : string,
  'size' : bigint,
  'enabled' : boolean,
  'buttonLabel' : string,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface Show {
  'id' : string,
  'flyer' : [] | [ExternalBlob],
  'status' : string,
  'title' : string,
  'venue' : string,
  'date' : Time,
  'ticketLink' : string,
  'location' : string,
}
export interface SocialMediaLink {
  'id' : string,
  'url' : string,
  'order' : bigint,
  'icon' : string,
  'platform' : string,
  'enabled' : boolean,
}
export interface StreamingPlatform {
  'url' : string,
  'platformLabel' : string,
  'platform' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface Task {
  'id' : string,
  'status' : TaskStatus,
  'title' : string,
  'assignedTo' : Array<string>,
  'description' : string,
  'deadline' : Time,
}
export type TaskStatus = { 'todo' : null } |
  { 'completed' : null } |
  { 'inProgress' : null };
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile { 'name' : string, 'email' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addCalendarEvent' : ActorMethod<[CalendarEvent], undefined>,
  'addContactMessage' : ActorMethod<[ContactMessage], undefined>,
  'addFile' : ActorMethod<[FileItem], undefined>,
  'addMediaItem' : ActorMethod<[MediaItem], undefined>,
  'addMessage' : ActorMethod<[Message], undefined>,
  'addProduct' : ActorMethod<[Product], undefined>,
  'addShow' : ActorMethod<[Show], undefined>,
  'addTask' : ActorMethod<[Task], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'deleteCalendarEvent' : ActorMethod<[string], undefined>,
  'deleteFile' : ActorMethod<[string], undefined>,
  'deleteMediaItem' : ActorMethod<[string], undefined>,
  'deleteProduct' : ActorMethod<[string], undefined>,
  'deleteShow' : ActorMethod<[string], undefined>,
  'deleteTask' : ActorMethod<[string], undefined>,
  'getAboutContent' : ActorMethod<[], AboutContent>,
  'getBookingConfig' : ActorMethod<[], BookingConfig>,
  'getCalendarEvents' : ActorMethod<[], Array<CalendarEvent>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCanisterStatus' : ActorMethod<[], CanisterStatus>,
  'getContactConfig' : ActorMethod<[], ContactConfig>,
  'getContactMessages' : ActorMethod<[], Array<ContactMessage>>,
  'getDesignConfig' : ActorMethod<[], DesignConfig>,
  'getFiles' : ActorMethod<[], Array<FileItem>>,
  'getHomepageConfig' : ActorMethod<[], HomepageConfig>,
  'getLegalContent' : ActorMethod<[], LegalContent>,
  'getMediaItems' : ActorMethod<[], Array<MediaItem>>,
  'getMessages' : ActorMethod<[], Array<Message>>,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'getShows' : ActorMethod<[], Array<Show>>,
  'getSocialMediaLinks' : ActorMethod<[], Array<SocialMediaLink>>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getTasks' : ActorMethod<[], Array<Task>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'makeGetOutcall' : ActorMethod<[string], string>,
  'markContactMessageAsRead' : ActorMethod<[string], undefined>,
  'recordTopUp' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateAboutContent' : ActorMethod<[AboutContent], undefined>,
  'updateBookingConfig' : ActorMethod<[BookingConfig], undefined>,
  'updateCalendarEvent' : ActorMethod<[CalendarEvent], undefined>,
  'updateContactConfig' : ActorMethod<[ContactConfig], undefined>,
  'updateDesignConfig' : ActorMethod<[DesignConfig], undefined>,
  'updateHomepageConfig' : ActorMethod<[HomepageConfig], undefined>,
  'updateLegalContent' : ActorMethod<[LegalContent], undefined>,
  'updateMediaItem' : ActorMethod<[MediaItem], undefined>,
  'updateProduct' : ActorMethod<[Product], undefined>,
  'updateProductOrder' : ActorMethod<[Array<string>], undefined>,
  'updateShow' : ActorMethod<[Show], undefined>,
  'updateSocialMediaLinks' : ActorMethod<[Array<SocialMediaLink>], undefined>,
  'updateTask' : ActorMethod<[Task], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];