/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Time = IDL.Int;
export const CalendarEvent = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'date' : Time,
  'description' : IDL.Text,
  'location' : IDL.Text,
});
export const ContactMessage = IDL.Record({
  'id' : IDL.Text,
  'subject' : IDL.Text,
  'name' : IDL.Text,
  'read' : IDL.Bool,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const FileItem = IDL.Record({
  'id' : IDL.Text,
  'file' : ExternalBlob,
  'name' : IDL.Text,
  'folder' : IDL.Text,
});
export const StreamingPlatform = IDL.Record({
  'url' : IDL.Text,
  'platformLabel' : IDL.Text,
  'platform' : IDL.Text,
});
export const AudioFile = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'duration' : IDL.Nat,
  'file' : ExternalBlob,
  'trackNumber' : IDL.Nat,
});
export const MediaType = IDL.Variant({
  'album' : IDL.Null,
  'video' : IDL.Null,
  'youtube' : IDL.Null,
  'single' : IDL.Null,
});
export const ImageFile = IDL.Record({
  'id' : IDL.Text,
  'file' : ExternalBlob,
  'isCover' : IDL.Bool,
});
export const MediaItem = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'createdAt' : Time,
  'description' : IDL.Text,
  'streamingPlatforms' : IDL.Vec(StreamingPlatform),
  'audioFiles' : IDL.Vec(AudioFile),
  'mediaType' : MediaType,
  'price' : IDL.Nat,
  'youtubeUrl' : IDL.Opt(IDL.Text),
  'images' : IDL.Vec(ImageFile),
});
export const Message = IDL.Record({
  'id' : IDL.Text,
  'content' : IDL.Text,
  'sender' : IDL.Text,
  'timestamp' : Time,
  'threadId' : IDL.Text,
});
export const ProductVariant = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'stock' : IDL.Nat,
  'price' : IDL.Nat,
});
export const Product = IDL.Record({
  'id' : IDL.Text,
  'categories' : IDL.Vec(IDL.Text),
  'order' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : Time,
  'description' : IDL.Text,
  'variants' : IDL.Vec(ProductVariant),
  'isDigital' : IDL.Bool,
  'images' : IDL.Vec(ExternalBlob),
});
export const Show = IDL.Record({
  'id' : IDL.Text,
  'flyer' : IDL.Opt(ExternalBlob),
  'status' : IDL.Text,
  'title' : IDL.Text,
  'venue' : IDL.Text,
  'date' : Time,
  'ticketLink' : IDL.Text,
  'location' : IDL.Text,
});
export const TaskStatus = IDL.Variant({
  'todo' : IDL.Null,
  'completed' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const Task = IDL.Record({
  'id' : IDL.Text,
  'status' : TaskStatus,
  'title' : IDL.Text,
  'assignedTo' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'deadline' : Time,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const AboutContent = IDL.Record({
  'bandMembers' : IDL.Vec(IDL.Text),
  'biography' : IDL.Text,
  'pressKit' : IDL.Opt(ExternalBlob),
  'photos' : IDL.Vec(ExternalBlob),
});
export const BookingFile = IDL.Record({
  'id' : IDL.Text,
  'file' : ExternalBlob,
  'name' : IDL.Text,
  'fileType' : IDL.Text,
});
export const BookingLink = IDL.Record({
  'id' : IDL.Text,
  'url' : IDL.Text,
  'linkLabel' : IDL.Text,
  'type' : IDL.Text,
});
export const BookingConfig = IDL.Record({
  'files' : IDL.Vec(BookingFile),
  'email' : IDL.Text,
  'links' : IDL.Vec(BookingLink),
  'callToAction' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
});
export const CanisterStatus = IDL.Record({
  'moduleHash' : IDL.Opt(IDL.Vec(IDL.Nat8)),
  'lastTopUpTime' : IDL.Opt(Time),
  'cycles' : IDL.Nat,
  'memorySize' : IDL.Nat,
  'canisterId' : IDL.Text,
  'lastMaintenanceCheck' : Time,
});
export const SocialMediaLink = IDL.Record({
  'id' : IDL.Text,
  'url' : IDL.Text,
  'order' : IDL.Nat,
  'icon' : IDL.Text,
  'platform' : IDL.Text,
  'enabled' : IDL.Bool,
});
export const ContactConfig = IDL.Record({
  'headline' : IDL.Text,
  'email' : IDL.Text,
  'socialMediaLinks' : IDL.Vec(SocialMediaLink),
});
export const HeroMediaType = IDL.Variant({
  'video' : IDL.Null,
  'image' : IDL.Null,
});
export const LogoVisibility = IDL.Record({
  'hero' : IDL.Bool,
  'header' : IDL.Bool,
});
export const ButtonStyle = IDL.Record({
  'backgroundColor' : IDL.Text,
  'borderRadius' : IDL.Nat,
  'hoverBackgroundColor' : IDL.Text,
  'borderStyle' : IDL.Text,
  'size' : IDL.Nat,
  'borderWidth' : IDL.Nat,
  'shape' : IDL.Text,
  'hoverTextColor' : IDL.Text,
  'hoverBorderColor' : IDL.Text,
  'borderColor' : IDL.Text,
  'textColor' : IDL.Text,
});
export const QuickButton = IDL.Record({
  'id' : IDL.Text,
  'url' : IDL.Text,
  'order' : IDL.Nat,
  'icon' : IDL.Text,
  'size' : IDL.Nat,
  'enabled' : IDL.Bool,
  'buttonLabel' : IDL.Text,
});
export const HeroVideo = IDL.Record({
  'muted' : IDL.Bool,
  'autoplay' : IDL.Bool,
  'file' : IDL.Opt(ExternalBlob),
  'externalUrl' : IDL.Opt(IDL.Text),
  'shouldLoop' : IDL.Bool,
});
export const DesignConfig = IDL.Record({
  'tagline' : IDL.Text,
  'logo' : IDL.Opt(ExternalBlob),
  'heroMediaType' : HeroMediaType,
  'heroSubtitle' : IDL.Text,
  'accentColor' : IDL.Text,
  'logoSize' : IDL.Nat,
  'heroImage' : IDL.Opt(ExternalBlob),
  'logoVisibility' : LogoVisibility,
  'heroTextColor' : IDL.Text,
  'heroTextSize' : IDL.Nat,
  'buttonStyle' : ButtonStyle,
  'quickButtons' : IDL.Vec(QuickButton),
  'heroVideo' : IDL.Opt(HeroVideo),
  'hoverOutlineColor' : IDL.Text,
});
export const HomepageConfig = IDL.Record({
  'autoUpcomingShows' : IDL.Bool,
  'latestReleaseId' : IDL.Opt(IDL.Text),
  'upcomingShowIds' : IDL.Vec(IDL.Text),
  'featuredProductIds' : IDL.Vec(IDL.Text),
});
export const LegalContent = IDL.Record({
  'privacyPolicy' : IDL.Text,
  'lastUpdated' : Time,
  'imprint' : IDL.Text,
  'termsOfService' : IDL.Text,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addCalendarEvent' : IDL.Func([CalendarEvent], [], []),
  'addContactMessage' : IDL.Func([ContactMessage], [], []),
  'addFile' : IDL.Func([FileItem], [], []),
  'addMediaItem' : IDL.Func([MediaItem], [], []),
  'addMessage' : IDL.Func([Message], [], []),
  'addProduct' : IDL.Func([Product], [], []),
  'addShow' : IDL.Func([Show], [], []),
  'addTask' : IDL.Func([Task], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'deleteCalendarEvent' : IDL.Func([IDL.Text], [], []),
  'deleteFile' : IDL.Func([IDL.Text], [], []),
  'deleteMediaItem' : IDL.Func([IDL.Text], [], []),
  'deleteProduct' : IDL.Func([IDL.Text], [], []),
  'deleteShow' : IDL.Func([IDL.Text], [], []),
  'deleteTask' : IDL.Func([IDL.Text], [], []),
  'getAboutContent' : IDL.Func([], [AboutContent], ['query']),
  'getBookingConfig' : IDL.Func([], [BookingConfig], ['query']),
  'getCalendarEvents' : IDL.Func([], [IDL.Vec(CalendarEvent)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCanisterStatus' : IDL.Func([], [CanisterStatus], []),
  'getContactConfig' : IDL.Func([], [ContactConfig], ['query']),
  'getContactMessages' : IDL.Func([], [IDL.Vec(ContactMessage)], ['query']),
  'getDesignConfig' : IDL.Func([], [DesignConfig], ['query']),
  'getFiles' : IDL.Func([], [IDL.Vec(FileItem)], ['query']),
  'getHomepageConfig' : IDL.Func([], [HomepageConfig], ['query']),
  'getLegalContent' : IDL.Func([], [LegalContent], ['query']),
  'getMediaItems' : IDL.Func([], [IDL.Vec(MediaItem)], ['query']),
  'getMessages' : IDL.Func([], [IDL.Vec(Message)], ['query']),
  'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getShows' : IDL.Func([], [IDL.Vec(Show)], ['query']),
  'getSocialMediaLinks' : IDL.Func([], [IDL.Vec(SocialMediaLink)], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'makeGetOutcall' : IDL.Func([IDL.Text], [IDL.Text], []),
  'markContactMessageAsRead' : IDL.Func([IDL.Text], [], []),
  'recordTopUp' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateAboutContent' : IDL.Func([AboutContent], [], []),
  'updateBookingConfig' : IDL.Func([BookingConfig], [], []),
  'updateCalendarEvent' : IDL.Func([CalendarEvent], [], []),
  'updateContactConfig' : IDL.Func([ContactConfig], [], []),
  'updateDesignConfig' : IDL.Func([DesignConfig], [], []),
  'updateHomepageConfig' : IDL.Func([HomepageConfig], [], []),
  'updateLegalContent' : IDL.Func([LegalContent], [], []),
  'updateMediaItem' : IDL.Func([MediaItem], [], []),
  'updateProduct' : IDL.Func([Product], [], []),
  'updateProductOrder' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
  'updateShow' : IDL.Func([Show], [], []),
  'updateSocialMediaLinks' : IDL.Func([IDL.Vec(SocialMediaLink)], [], []),
  'updateTask' : IDL.Func([Task], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Time = IDL.Int;
  const CalendarEvent = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'date' : Time,
    'description' : IDL.Text,
    'location' : IDL.Text,
  });
  const ContactMessage = IDL.Record({
    'id' : IDL.Text,
    'subject' : IDL.Text,
    'name' : IDL.Text,
    'read' : IDL.Bool,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const FileItem = IDL.Record({
    'id' : IDL.Text,
    'file' : ExternalBlob,
    'name' : IDL.Text,
    'folder' : IDL.Text,
  });
  const StreamingPlatform = IDL.Record({
    'url' : IDL.Text,
    'platformLabel' : IDL.Text,
    'platform' : IDL.Text,
  });
  const AudioFile = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'duration' : IDL.Nat,
    'file' : ExternalBlob,
    'trackNumber' : IDL.Nat,
  });
  const MediaType = IDL.Variant({
    'album' : IDL.Null,
    'video' : IDL.Null,
    'youtube' : IDL.Null,
    'single' : IDL.Null,
  });
  const ImageFile = IDL.Record({
    'id' : IDL.Text,
    'file' : ExternalBlob,
    'isCover' : IDL.Bool,
  });
  const MediaItem = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'createdAt' : Time,
    'description' : IDL.Text,
    'streamingPlatforms' : IDL.Vec(StreamingPlatform),
    'audioFiles' : IDL.Vec(AudioFile),
    'mediaType' : MediaType,
    'price' : IDL.Nat,
    'youtubeUrl' : IDL.Opt(IDL.Text),
    'images' : IDL.Vec(ImageFile),
  });
  const Message = IDL.Record({
    'id' : IDL.Text,
    'content' : IDL.Text,
    'sender' : IDL.Text,
    'timestamp' : Time,
    'threadId' : IDL.Text,
  });
  const ProductVariant = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'stock' : IDL.Nat,
    'price' : IDL.Nat,
  });
  const Product = IDL.Record({
    'id' : IDL.Text,
    'categories' : IDL.Vec(IDL.Text),
    'order' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : Time,
    'description' : IDL.Text,
    'variants' : IDL.Vec(ProductVariant),
    'isDigital' : IDL.Bool,
    'images' : IDL.Vec(ExternalBlob),
  });
  const Show = IDL.Record({
    'id' : IDL.Text,
    'flyer' : IDL.Opt(ExternalBlob),
    'status' : IDL.Text,
    'title' : IDL.Text,
    'venue' : IDL.Text,
    'date' : Time,
    'ticketLink' : IDL.Text,
    'location' : IDL.Text,
  });
  const TaskStatus = IDL.Variant({
    'todo' : IDL.Null,
    'completed' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const Task = IDL.Record({
    'id' : IDL.Text,
    'status' : TaskStatus,
    'title' : IDL.Text,
    'assignedTo' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'deadline' : Time,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const AboutContent = IDL.Record({
    'bandMembers' : IDL.Vec(IDL.Text),
    'biography' : IDL.Text,
    'pressKit' : IDL.Opt(ExternalBlob),
    'photos' : IDL.Vec(ExternalBlob),
  });
  const BookingFile = IDL.Record({
    'id' : IDL.Text,
    'file' : ExternalBlob,
    'name' : IDL.Text,
    'fileType' : IDL.Text,
  });
  const BookingLink = IDL.Record({
    'id' : IDL.Text,
    'url' : IDL.Text,
    'linkLabel' : IDL.Text,
    'type' : IDL.Text,
  });
  const BookingConfig = IDL.Record({
    'files' : IDL.Vec(BookingFile),
    'email' : IDL.Text,
    'links' : IDL.Vec(BookingLink),
    'callToAction' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'email' : IDL.Text });
  const CanisterStatus = IDL.Record({
    'moduleHash' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'lastTopUpTime' : IDL.Opt(Time),
    'cycles' : IDL.Nat,
    'memorySize' : IDL.Nat,
    'canisterId' : IDL.Text,
    'lastMaintenanceCheck' : Time,
  });
  const SocialMediaLink = IDL.Record({
    'id' : IDL.Text,
    'url' : IDL.Text,
    'order' : IDL.Nat,
    'icon' : IDL.Text,
    'platform' : IDL.Text,
    'enabled' : IDL.Bool,
  });
  const ContactConfig = IDL.Record({
    'headline' : IDL.Text,
    'email' : IDL.Text,
    'socialMediaLinks' : IDL.Vec(SocialMediaLink),
  });
  const HeroMediaType = IDL.Variant({ 'video' : IDL.Null, 'image' : IDL.Null });
  const LogoVisibility = IDL.Record({ 'hero' : IDL.Bool, 'header' : IDL.Bool });
  const ButtonStyle = IDL.Record({
    'backgroundColor' : IDL.Text,
    'borderRadius' : IDL.Nat,
    'hoverBackgroundColor' : IDL.Text,
    'borderStyle' : IDL.Text,
    'size' : IDL.Nat,
    'borderWidth' : IDL.Nat,
    'shape' : IDL.Text,
    'hoverTextColor' : IDL.Text,
    'hoverBorderColor' : IDL.Text,
    'borderColor' : IDL.Text,
    'textColor' : IDL.Text,
  });
  const QuickButton = IDL.Record({
    'id' : IDL.Text,
    'url' : IDL.Text,
    'order' : IDL.Nat,
    'icon' : IDL.Text,
    'size' : IDL.Nat,
    'enabled' : IDL.Bool,
    'buttonLabel' : IDL.Text,
  });
  const HeroVideo = IDL.Record({
    'muted' : IDL.Bool,
    'autoplay' : IDL.Bool,
    'file' : IDL.Opt(ExternalBlob),
    'externalUrl' : IDL.Opt(IDL.Text),
    'shouldLoop' : IDL.Bool,
  });
  const DesignConfig = IDL.Record({
    'tagline' : IDL.Text,
    'logo' : IDL.Opt(ExternalBlob),
    'heroMediaType' : HeroMediaType,
    'heroSubtitle' : IDL.Text,
    'accentColor' : IDL.Text,
    'logoSize' : IDL.Nat,
    'heroImage' : IDL.Opt(ExternalBlob),
    'logoVisibility' : LogoVisibility,
    'heroTextColor' : IDL.Text,
    'heroTextSize' : IDL.Nat,
    'buttonStyle' : ButtonStyle,
    'quickButtons' : IDL.Vec(QuickButton),
    'heroVideo' : IDL.Opt(HeroVideo),
    'hoverOutlineColor' : IDL.Text,
  });
  const HomepageConfig = IDL.Record({
    'autoUpcomingShows' : IDL.Bool,
    'latestReleaseId' : IDL.Opt(IDL.Text),
    'upcomingShowIds' : IDL.Vec(IDL.Text),
    'featuredProductIds' : IDL.Vec(IDL.Text),
  });
  const LegalContent = IDL.Record({
    'privacyPolicy' : IDL.Text,
    'lastUpdated' : Time,
    'imprint' : IDL.Text,
    'termsOfService' : IDL.Text,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addCalendarEvent' : IDL.Func([CalendarEvent], [], []),
    'addContactMessage' : IDL.Func([ContactMessage], [], []),
    'addFile' : IDL.Func([FileItem], [], []),
    'addMediaItem' : IDL.Func([MediaItem], [], []),
    'addMessage' : IDL.Func([Message], [], []),
    'addProduct' : IDL.Func([Product], [], []),
    'addShow' : IDL.Func([Show], [], []),
    'addTask' : IDL.Func([Task], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'deleteCalendarEvent' : IDL.Func([IDL.Text], [], []),
    'deleteFile' : IDL.Func([IDL.Text], [], []),
    'deleteMediaItem' : IDL.Func([IDL.Text], [], []),
    'deleteProduct' : IDL.Func([IDL.Text], [], []),
    'deleteShow' : IDL.Func([IDL.Text], [], []),
    'deleteTask' : IDL.Func([IDL.Text], [], []),
    'getAboutContent' : IDL.Func([], [AboutContent], ['query']),
    'getBookingConfig' : IDL.Func([], [BookingConfig], ['query']),
    'getCalendarEvents' : IDL.Func([], [IDL.Vec(CalendarEvent)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCanisterStatus' : IDL.Func([], [CanisterStatus], []),
    'getContactConfig' : IDL.Func([], [ContactConfig], ['query']),
    'getContactMessages' : IDL.Func([], [IDL.Vec(ContactMessage)], ['query']),
    'getDesignConfig' : IDL.Func([], [DesignConfig], ['query']),
    'getFiles' : IDL.Func([], [IDL.Vec(FileItem)], ['query']),
    'getHomepageConfig' : IDL.Func([], [HomepageConfig], ['query']),
    'getLegalContent' : IDL.Func([], [LegalContent], ['query']),
    'getMediaItems' : IDL.Func([], [IDL.Vec(MediaItem)], ['query']),
    'getMessages' : IDL.Func([], [IDL.Vec(Message)], ['query']),
    'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getShows' : IDL.Func([], [IDL.Vec(Show)], ['query']),
    'getSocialMediaLinks' : IDL.Func([], [IDL.Vec(SocialMediaLink)], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'makeGetOutcall' : IDL.Func([IDL.Text], [IDL.Text], []),
    'markContactMessageAsRead' : IDL.Func([IDL.Text], [], []),
    'recordTopUp' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateAboutContent' : IDL.Func([AboutContent], [], []),
    'updateBookingConfig' : IDL.Func([BookingConfig], [], []),
    'updateCalendarEvent' : IDL.Func([CalendarEvent], [], []),
    'updateContactConfig' : IDL.Func([ContactConfig], [], []),
    'updateDesignConfig' : IDL.Func([DesignConfig], [], []),
    'updateHomepageConfig' : IDL.Func([HomepageConfig], [], []),
    'updateLegalContent' : IDL.Func([LegalContent], [], []),
    'updateMediaItem' : IDL.Func([MediaItem], [], []),
    'updateProduct' : IDL.Func([Product], [], []),
    'updateProductOrder' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
    'updateShow' : IDL.Func([Show], [], []),
    'updateSocialMediaLinks' : IDL.Func([IDL.Vec(SocialMediaLink)], [], []),
    'updateTask' : IDL.Func([Task], [], []),
  });
};

export const init = ({ IDL }) => { return []; };