/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface AboutContent {
    bandMembers: Array<string>;
    biography: string;
    pressKit?: ExternalBlob;
    photos: Array<ExternalBlob>;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type Time = bigint;
export interface LegalContent {
    privacyPolicy: string;
    lastUpdated: Time;
    imprint: string;
    termsOfService: string;
}
export interface ImageFile {
    id: string;
    file: ExternalBlob;
    isCover: boolean;
}
export interface Task {
    id: string;
    status: TaskStatus;
    title: string;
    assignedTo: Array<string>;
    description: string;
    deadline: Time;
}
export interface SocialMediaLink {
    id: string;
    url: string;
    order: bigint;
    icon: string;
    platform: string;
    enabled: boolean;
}
export interface MediaItem {
    id: string;
    title: string;
    createdAt: Time;
    description: string;
    streamingPlatforms: Array<StreamingPlatform>;
    audioFiles: Array<AudioFile>;
    mediaType: MediaType;
    price: bigint;
    youtubeUrl?: string;
    images: Array<ImageFile>;
}
export interface _ImmutableObjectStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface HomepageConfig {
    autoUpcomingShows: boolean;
    latestReleaseId?: string;
    upcomingShowIds: Array<string>;
    featuredProductIds: Array<string>;
}
export interface ContactMessage {
    id: string;
    subject: string;
    name: string;
    read: boolean;
    email: string;
    message: string;
    timestamp: Time;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface DesignConfig {
    tagline: string;
    logo?: ExternalBlob;
    heroMediaType: HeroMediaType;
    heroSubtitle: string;
    accentColor: string;
    logoSize: bigint;
    heroImage?: ExternalBlob;
    logoVisibility: LogoVisibility;
    heroTextColor: string;
    heroTextSize: bigint;
    buttonStyle: ButtonStyle;
    quickButtons: Array<QuickButton>;
    heroVideo?: HeroVideo;
    hoverOutlineColor: string;
}
export interface StreamingPlatform {
    url: string;
    platformLabel: string;
    platform: string;
}
export type StripeSessionStatus = {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
};
export interface StripeConfiguration {
    allowedCountries: Array<string>;
    secretKey: string;
}
export interface BookingLink {
    id: string;
    url: string;
    linkLabel: string;
    type: string;
}
export interface FileItem {
    id: string;
    file: ExternalBlob;
    name: string;
    folder: string;
}
export interface ContactConfig {
    headline: string;
    email: string;
    socialMediaLinks: Array<SocialMediaLink>;
}
export interface QuickButton {
    id: string;
    url: string;
    order: bigint;
    icon: string;
    size: bigint;
    enabled: boolean;
    buttonLabel: string;
}
export interface BookingConfig {
    files: Array<BookingFile>;
    email: string;
    links: Array<BookingLink>;
    callToAction: string;
}
export interface LogoVisibility {
    hero: boolean;
    header: boolean;
}
export interface _ImmutableObjectStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _ImmutableObjectStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface BookingFile {
    id: string;
    file: ExternalBlob;
    name: string;
    fileType: string;
}
export interface ProductVariant {
    id: string;
    name: string;
    stock: bigint;
    price: bigint;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface ButtonStyle {
    backgroundColor: string;
    borderRadius: bigint;
    hoverBackgroundColor: string;
    borderStyle: string;
    size: bigint;
    borderWidth: bigint;
    shape: string;
    hoverTextColor: string;
    hoverBorderColor: string;
    borderColor: string;
    textColor: string;
}
export interface AudioFile {
    id: string;
    title: string;
    duration: bigint;
    file: ExternalBlob;
    trackNumber: bigint;
}
export interface ShoppingItem {
    productName: string;
    currency: string;
    quantity: bigint;
    priceInCents: bigint;
    productDescription: string;
}
export interface CalendarEvent {
    id: string;
    title: string;
    date: Time;
    description: string;
    location: string;
}
export interface Show {
    id: string;
    flyer?: ExternalBlob;
    status: string;
    title: string;
    venue: string;
    date: Time;
    ticketLink: string;
    location: string;
}
export interface Message {
    id: string;
    content: string;
    sender: string;
    timestamp: Time;
    threadId: string;
}
export interface CanisterStatus {
    moduleHash?: Uint8Array;
    lastTopUpTime?: Time;
    cycles: bigint;
    memorySize: bigint;
    canisterId: string;
    lastMaintenanceCheck: Time;
}
export interface HeroVideo {
    muted: boolean;
    autoplay: boolean;
    file?: ExternalBlob;
    externalUrl?: string;
    shouldLoop: boolean;
}
export interface UserProfile {
    name: string;
    email: string;
}
export interface Product {
    id: string;
    categories: Array<string>;
    order: bigint;
    name: string;
    createdAt: Time;
    description: string;
    variants: Array<ProductVariant>;
    isDigital: boolean;
    images: Array<ExternalBlob>;
}
export enum HeroMediaType {
    video = "video",
    image = "image"
}
export enum MediaType {
    album = "album",
    video = "video",
    youtube = "youtube",
    single = "single"
}
export enum TaskStatus {
    todo = "todo",
    completed = "completed",
    inProgress = "inProgress"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _immutableObjectStorageBlobsAreLive(hashes: Array<Uint8Array>): Promise<Array<boolean>>;
    _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _immutableObjectStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _immutableObjectStorageCreateCertificate(blobHash: string): Promise<_ImmutableObjectStorageCreateCertificateResult>;
    _immutableObjectStorageRefillCashier(refillInformation: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult>;
    _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControl(): Promise<void>;
    addCalendarEvent(event: CalendarEvent): Promise<void>;
    addContactMessage(message: ContactMessage): Promise<void>;
    addFile(file: FileItem): Promise<void>;
    addMediaItem(item: MediaItem): Promise<void>;
    addMessage(message: Message): Promise<void>;
    addProduct(product: Product): Promise<void>;
    addShow(show: Show): Promise<void>;
    addTask(task: Task): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createCheckoutSession(items: Array<ShoppingItem>, successUrl: string, cancelUrl: string): Promise<string>;
    deleteCalendarEvent(id: string): Promise<void>;
    deleteFile(id: string): Promise<void>;
    deleteMediaItem(id: string): Promise<void>;
    deleteProduct(id: string): Promise<void>;
    deleteShow(id: string): Promise<void>;
    deleteTask(id: string): Promise<void>;
    getAboutContent(): Promise<AboutContent>;
    getBookingConfig(): Promise<BookingConfig>;
    getCalendarEvents(): Promise<Array<CalendarEvent>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCanisterStatus(): Promise<CanisterStatus>;
    getContactConfig(): Promise<ContactConfig>;
    getContactMessages(): Promise<Array<ContactMessage>>;
    getDesignConfig(): Promise<DesignConfig>;
    getFiles(): Promise<Array<FileItem>>;
    getHomepageConfig(): Promise<HomepageConfig>;
    getLegalContent(): Promise<LegalContent>;
    getMediaItems(): Promise<Array<MediaItem>>;
    getMessages(): Promise<Array<Message>>;
    getProducts(): Promise<Array<Product>>;
    getShows(): Promise<Array<Show>>;
    getSocialMediaLinks(): Promise<Array<SocialMediaLink>>;
    getStripeSessionStatus(sessionId: string): Promise<StripeSessionStatus>;
    getTasks(): Promise<Array<Task>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    isStripeConfigured(): Promise<boolean>;
    makeGetOutcall(url: string): Promise<string>;
    markContactMessageAsRead(id: string): Promise<void>;
    recordTopUp(): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setStripeConfiguration(config: StripeConfiguration): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateAboutContent(content: AboutContent): Promise<void>;
    updateBookingConfig(config: BookingConfig): Promise<void>;
    updateCalendarEvent(event: CalendarEvent): Promise<void>;
    updateContactConfig(config: ContactConfig): Promise<void>;
    updateDesignConfig(config: DesignConfig): Promise<void>;
    updateHomepageConfig(config: HomepageConfig): Promise<void>;
    updateLegalContent(content: LegalContent): Promise<void>;
    updateMediaItem(item: MediaItem): Promise<void>;
    updateProduct(product: Product): Promise<void>;
    updateProductOrder(productIds: Array<string>): Promise<void>;
    updateShow(show: Show): Promise<void>;
    updateSocialMediaLinks(links: Array<SocialMediaLink>): Promise<void>;
    updateTask(task: Task): Promise<void>;
}
import type { AboutContent as _AboutContent, AudioFile as _AudioFile, BookingConfig as _BookingConfig, BookingFile as _BookingFile, BookingLink as _BookingLink, ButtonStyle as _ButtonStyle, CanisterStatus as _CanisterStatus, DesignConfig as _DesignConfig, ExternalBlob as _ExternalBlob, FileItem as _FileItem, HeroMediaType as _HeroMediaType, HeroVideo as _HeroVideo, HomepageConfig as _HomepageConfig, ImageFile as _ImageFile, LogoVisibility as _LogoVisibility, MediaItem as _MediaItem, MediaType as _MediaType, Product as _Product, ProductVariant as _ProductVariant, QuickButton as _QuickButton, Show as _Show, StreamingPlatform as _StreamingPlatform, StripeSessionStatus as _StripeSessionStatus, Task as _Task, TaskStatus as _TaskStatus, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, _ImmutableObjectStorageRefillInformation as __ImmutableObjectStorageRefillInformation, _ImmutableObjectStorageRefillResult as __ImmutableObjectStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _immutableObjectStorageBlobsAreLive(arg0: Array<Uint8Array>): Promise<Array<boolean>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
            return result;
        }
    }
    async _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsToDelete();
            return result;
        }
    }
    async _immutableObjectStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _immutableObjectStorageCreateCertificate(arg0: string): Promise<_ImmutableObjectStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _immutableObjectStorageRefillCashier(arg0: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async addCalendarEvent(arg0: CalendarEvent): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addCalendarEvent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCalendarEvent(arg0);
            return result;
        }
    }
    async addContactMessage(arg0: ContactMessage): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addContactMessage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addContactMessage(arg0);
            return result;
        }
    }
    async addFile(arg0: FileItem): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addFile(await to_candid_FileItem_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addFile(await to_candid_FileItem_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addMediaItem(arg0: MediaItem): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addMediaItem(await to_candid_MediaItem_n11(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMediaItem(await to_candid_MediaItem_n11(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addMessage(arg0: Message): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addMessage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMessage(arg0);
            return result;
        }
    }
    async addProduct(arg0: Product): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addProduct(await to_candid_Product_n21(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProduct(await to_candid_Product_n21(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addShow(arg0: Show): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addShow(await to_candid_Show_n24(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addShow(await to_candid_Show_n24(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addTask(arg0: Task): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addTask(to_candid_Task_n26(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTask(to_candid_Task_n26(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n30(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n30(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createCheckoutSession(arg0: Array<ShoppingItem>, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
            return result;
        }
    }
    async deleteCalendarEvent(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCalendarEvent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCalendarEvent(arg0);
            return result;
        }
    }
    async deleteFile(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteFile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteFile(arg0);
            return result;
        }
    }
    async deleteMediaItem(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMediaItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMediaItem(arg0);
            return result;
        }
    }
    async deleteProduct(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProduct(arg0);
            return result;
        }
    }
    async deleteShow(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteShow(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteShow(arg0);
            return result;
        }
    }
    async deleteTask(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteTask(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteTask(arg0);
            return result;
        }
    }
    async getAboutContent(): Promise<AboutContent> {
        if (this.processError) {
            try {
                const result = await this.actor.getAboutContent();
                return from_candid_AboutContent_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAboutContent();
            return from_candid_AboutContent_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBookingConfig(): Promise<BookingConfig> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookingConfig();
                return from_candid_BookingConfig_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookingConfig();
            return from_candid_BookingConfig_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCalendarEvents(): Promise<Array<CalendarEvent>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCalendarEvents();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCalendarEvents();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCanisterStatus(): Promise<CanisterStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getCanisterStatus();
                return from_candid_CanisterStatus_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCanisterStatus();
            return from_candid_CanisterStatus_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getContactConfig(): Promise<ContactConfig> {
        if (this.processError) {
            try {
                const result = await this.actor.getContactConfig();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContactConfig();
            return result;
        }
    }
    async getContactMessages(): Promise<Array<ContactMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getContactMessages();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContactMessages();
            return result;
        }
    }
    async getDesignConfig(): Promise<DesignConfig> {
        if (this.processError) {
            try {
                const result = await this.actor.getDesignConfig();
                return from_candid_DesignConfig_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDesignConfig();
            return from_candid_DesignConfig_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFiles(): Promise<Array<FileItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFiles();
                return from_candid_vec_n57(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFiles();
            return from_candid_vec_n57(this._uploadFile, this._downloadFile, result);
        }
    }
    async getHomepageConfig(): Promise<HomepageConfig> {
        if (this.processError) {
            try {
                const result = await this.actor.getHomepageConfig();
                return from_candid_HomepageConfig_n60(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHomepageConfig();
            return from_candid_HomepageConfig_n60(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLegalContent(): Promise<LegalContent> {
        if (this.processError) {
            try {
                const result = await this.actor.getLegalContent();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLegalContent();
            return result;
        }
    }
    async getMediaItems(): Promise<Array<MediaItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMediaItems();
                return from_candid_vec_n62(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMediaItems();
            return from_candid_vec_n62(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMessages(): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMessages();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMessages();
            return result;
        }
    }
    async getProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProducts();
                return from_candid_vec_n73(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProducts();
            return from_candid_vec_n73(this._uploadFile, this._downloadFile, result);
        }
    }
    async getShows(): Promise<Array<Show>> {
        if (this.processError) {
            try {
                const result = await this.actor.getShows();
                return from_candid_vec_n76(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getShows();
            return from_candid_vec_n76(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSocialMediaLinks(): Promise<Array<SocialMediaLink>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSocialMediaLinks();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSocialMediaLinks();
            return result;
        }
    }
    async getStripeSessionStatus(arg0: string): Promise<StripeSessionStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getStripeSessionStatus(arg0);
                return from_candid_StripeSessionStatus_n79(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStripeSessionStatus(arg0);
            return from_candid_StripeSessionStatus_n79(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTasks(): Promise<Array<Task>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTasks();
                return from_candid_vec_n82(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTasks();
            return from_candid_vec_n82(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isStripeConfigured(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isStripeConfigured();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isStripeConfigured();
            return result;
        }
    }
    async makeGetOutcall(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.makeGetOutcall(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.makeGetOutcall(arg0);
            return result;
        }
    }
    async markContactMessageAsRead(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markContactMessageAsRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markContactMessageAsRead(arg0);
            return result;
        }
    }
    async recordTopUp(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordTopUp();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordTopUp();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async setStripeConfiguration(arg0: StripeConfiguration): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setStripeConfiguration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setStripeConfiguration(arg0);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateAboutContent(arg0: AboutContent): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAboutContent(await to_candid_AboutContent_n87(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAboutContent(await to_candid_AboutContent_n87(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateBookingConfig(arg0: BookingConfig): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBookingConfig(await to_candid_BookingConfig_n89(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBookingConfig(await to_candid_BookingConfig_n89(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateCalendarEvent(arg0: CalendarEvent): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCalendarEvent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCalendarEvent(arg0);
            return result;
        }
    }
    async updateContactConfig(arg0: ContactConfig): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateContactConfig(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateContactConfig(arg0);
            return result;
        }
    }
    async updateDesignConfig(arg0: DesignConfig): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDesignConfig(await to_candid_DesignConfig_n94(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDesignConfig(await to_candid_DesignConfig_n94(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateHomepageConfig(arg0: HomepageConfig): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateHomepageConfig(to_candid_HomepageConfig_n100(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateHomepageConfig(to_candid_HomepageConfig_n100(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateLegalContent(arg0: LegalContent): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLegalContent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLegalContent(arg0);
            return result;
        }
    }
    async updateMediaItem(arg0: MediaItem): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMediaItem(await to_candid_MediaItem_n11(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMediaItem(await to_candid_MediaItem_n11(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateProduct(arg0: Product): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProduct(await to_candid_Product_n21(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProduct(await to_candid_Product_n21(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateProductOrder(arg0: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProductOrder(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProductOrder(arg0);
            return result;
        }
    }
    async updateShow(arg0: Show): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateShow(await to_candid_Show_n24(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateShow(await to_candid_Show_n24(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateSocialMediaLinks(arg0: Array<SocialMediaLink>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSocialMediaLinks(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSocialMediaLinks(arg0);
            return result;
        }
    }
    async updateTask(arg0: Task): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTask(to_candid_Task_n26(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTask(to_candid_Task_n26(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
async function from_candid_AboutContent_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AboutContent): Promise<AboutContent> {
    return await from_candid_record_n33(_uploadFile, _downloadFile, value);
}
async function from_candid_AudioFile_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AudioFile): Promise<AudioFile> {
    return await from_candid_record_n67(_uploadFile, _downloadFile, value);
}
async function from_candid_BookingConfig_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BookingConfig): Promise<BookingConfig> {
    return await from_candid_record_n38(_uploadFile, _downloadFile, value);
}
async function from_candid_BookingFile_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BookingFile): Promise<BookingFile> {
    return await from_candid_record_n41(_uploadFile, _downloadFile, value);
}
function from_candid_CanisterStatus_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CanisterStatus): CanisterStatus {
    return from_candid_record_n46(_uploadFile, _downloadFile, value);
}
async function from_candid_DesignConfig_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DesignConfig): Promise<DesignConfig> {
    return await from_candid_record_n50(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
async function from_candid_FileItem_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FileItem): Promise<FileItem> {
    return await from_candid_record_n59(_uploadFile, _downloadFile, value);
}
function from_candid_HeroMediaType_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _HeroMediaType): HeroMediaType {
    return from_candid_variant_n52(_uploadFile, _downloadFile, value);
}
async function from_candid_HeroVideo_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _HeroVideo): Promise<HeroVideo> {
    return await from_candid_record_n55(_uploadFile, _downloadFile, value);
}
function from_candid_HomepageConfig_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _HomepageConfig): HomepageConfig {
    return from_candid_record_n61(_uploadFile, _downloadFile, value);
}
async function from_candid_ImageFile_n71(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImageFile): Promise<ImageFile> {
    return await from_candid_record_n72(_uploadFile, _downloadFile, value);
}
async function from_candid_MediaItem_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MediaItem): Promise<MediaItem> {
    return await from_candid_record_n64(_uploadFile, _downloadFile, value);
}
function from_candid_MediaType_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MediaType): MediaType {
    return from_candid_variant_n69(_uploadFile, _downloadFile, value);
}
async function from_candid_Product_n74(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Product): Promise<Product> {
    return await from_candid_record_n75(_uploadFile, _downloadFile, value);
}
async function from_candid_Show_n77(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Show): Promise<Show> {
    return await from_candid_record_n78(_uploadFile, _downloadFile, value);
}
function from_candid_StripeSessionStatus_n79(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StripeSessionStatus): StripeSessionStatus {
    return from_candid_variant_n80(_uploadFile, _downloadFile, value);
}
function from_candid_TaskStatus_n85(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TaskStatus): TaskStatus {
    return from_candid_variant_n86(_uploadFile, _downloadFile, value);
}
function from_candid_Task_n83(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Task): Task {
    return from_candid_record_n84(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n44(_uploadFile, _downloadFile, value);
}
function from_candid__ImmutableObjectStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __ImmutableObjectStorageRefillResult): _ImmutableObjectStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n35(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Uint8Array]): Uint8Array | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_HeroVideo]): Promise<HeroVideo | null> {
    return value.length === 0 ? null : await from_candid_HeroVideo_n54(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bandMembers: Array<string>;
    biography: string;
    pressKit: [] | [_ExternalBlob];
    photos: Array<_ExternalBlob>;
}): Promise<{
    bandMembers: Array<string>;
    biography: string;
    pressKit?: ExternalBlob;
    photos: Array<ExternalBlob>;
}> {
    return {
        bandMembers: value.bandMembers,
        biography: value.biography,
        pressKit: record_opt_to_undefined(await from_candid_opt_n34(_uploadFile, _downloadFile, value.pressKit)),
        photos: await from_candid_vec_n36(_uploadFile, _downloadFile, value.photos)
    };
}
async function from_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    files: Array<_BookingFile>;
    email: string;
    links: Array<_BookingLink>;
    callToAction: string;
}): Promise<{
    files: Array<BookingFile>;
    email: string;
    links: Array<BookingLink>;
    callToAction: string;
}> {
    return {
        files: await from_candid_vec_n39(_uploadFile, _downloadFile, value.files),
        email: value.email,
        links: value.links,
        callToAction: value.callToAction
    };
}
async function from_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    file: _ExternalBlob;
    name: string;
    fileType: string;
}): Promise<{
    id: string;
    file: ExternalBlob;
    name: string;
    fileType: string;
}> {
    return {
        id: value.id,
        file: await from_candid_ExternalBlob_n35(_uploadFile, _downloadFile, value.file),
        name: value.name,
        fileType: value.fileType
    };
}
function from_candid_record_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    moduleHash: [] | [Uint8Array];
    lastTopUpTime: [] | [_Time];
    cycles: bigint;
    memorySize: bigint;
    canisterId: string;
    lastMaintenanceCheck: _Time;
}): {
    moduleHash?: Uint8Array;
    lastTopUpTime?: Time;
    cycles: bigint;
    memorySize: bigint;
    canisterId: string;
    lastMaintenanceCheck: Time;
} {
    return {
        moduleHash: record_opt_to_undefined(from_candid_opt_n47(_uploadFile, _downloadFile, value.moduleHash)),
        lastTopUpTime: record_opt_to_undefined(from_candid_opt_n48(_uploadFile, _downloadFile, value.lastTopUpTime)),
        cycles: value.cycles,
        memorySize: value.memorySize,
        canisterId: value.canisterId,
        lastMaintenanceCheck: value.lastMaintenanceCheck
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
async function from_candid_record_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    tagline: string;
    logo: [] | [_ExternalBlob];
    heroMediaType: _HeroMediaType;
    heroSubtitle: string;
    accentColor: string;
    logoSize: bigint;
    heroImage: [] | [_ExternalBlob];
    logoVisibility: _LogoVisibility;
    heroTextColor: string;
    heroTextSize: bigint;
    buttonStyle: _ButtonStyle;
    quickButtons: Array<_QuickButton>;
    heroVideo: [] | [_HeroVideo];
    hoverOutlineColor: string;
}): Promise<{
    tagline: string;
    logo?: ExternalBlob;
    heroMediaType: HeroMediaType;
    heroSubtitle: string;
    accentColor: string;
    logoSize: bigint;
    heroImage?: ExternalBlob;
    logoVisibility: LogoVisibility;
    heroTextColor: string;
    heroTextSize: bigint;
    buttonStyle: ButtonStyle;
    quickButtons: Array<QuickButton>;
    heroVideo?: HeroVideo;
    hoverOutlineColor: string;
}> {
    return {
        tagline: value.tagline,
        logo: record_opt_to_undefined(await from_candid_opt_n34(_uploadFile, _downloadFile, value.logo)),
        heroMediaType: from_candid_HeroMediaType_n51(_uploadFile, _downloadFile, value.heroMediaType),
        heroSubtitle: value.heroSubtitle,
        accentColor: value.accentColor,
        logoSize: value.logoSize,
        heroImage: record_opt_to_undefined(await from_candid_opt_n34(_uploadFile, _downloadFile, value.heroImage)),
        logoVisibility: value.logoVisibility,
        heroTextColor: value.heroTextColor,
        heroTextSize: value.heroTextSize,
        buttonStyle: value.buttonStyle,
        quickButtons: value.quickButtons,
        heroVideo: record_opt_to_undefined(await from_candid_opt_n53(_uploadFile, _downloadFile, value.heroVideo)),
        hoverOutlineColor: value.hoverOutlineColor
    };
}
async function from_candid_record_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    muted: boolean;
    autoplay: boolean;
    file: [] | [_ExternalBlob];
    externalUrl: [] | [string];
    shouldLoop: boolean;
}): Promise<{
    muted: boolean;
    autoplay: boolean;
    file?: ExternalBlob;
    externalUrl?: string;
    shouldLoop: boolean;
}> {
    return {
        muted: value.muted,
        autoplay: value.autoplay,
        file: record_opt_to_undefined(await from_candid_opt_n34(_uploadFile, _downloadFile, value.file)),
        externalUrl: record_opt_to_undefined(from_candid_opt_n56(_uploadFile, _downloadFile, value.externalUrl)),
        shouldLoop: value.shouldLoop
    };
}
async function from_candid_record_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    file: _ExternalBlob;
    name: string;
    folder: string;
}): Promise<{
    id: string;
    file: ExternalBlob;
    name: string;
    folder: string;
}> {
    return {
        id: value.id,
        file: await from_candid_ExternalBlob_n35(_uploadFile, _downloadFile, value.file),
        name: value.name,
        folder: value.folder
    };
}
function from_candid_record_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    autoUpcomingShows: boolean;
    latestReleaseId: [] | [string];
    upcomingShowIds: Array<string>;
    featuredProductIds: Array<string>;
}): {
    autoUpcomingShows: boolean;
    latestReleaseId?: string;
    upcomingShowIds: Array<string>;
    featuredProductIds: Array<string>;
} {
    return {
        autoUpcomingShows: value.autoUpcomingShows,
        latestReleaseId: record_opt_to_undefined(from_candid_opt_n56(_uploadFile, _downloadFile, value.latestReleaseId)),
        upcomingShowIds: value.upcomingShowIds,
        featuredProductIds: value.featuredProductIds
    };
}
async function from_candid_record_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    createdAt: _Time;
    description: string;
    streamingPlatforms: Array<_StreamingPlatform>;
    audioFiles: Array<_AudioFile>;
    mediaType: _MediaType;
    price: bigint;
    youtubeUrl: [] | [string];
    images: Array<_ImageFile>;
}): Promise<{
    id: string;
    title: string;
    createdAt: Time;
    description: string;
    streamingPlatforms: Array<StreamingPlatform>;
    audioFiles: Array<AudioFile>;
    mediaType: MediaType;
    price: bigint;
    youtubeUrl?: string;
    images: Array<ImageFile>;
}> {
    return {
        id: value.id,
        title: value.title,
        createdAt: value.createdAt,
        description: value.description,
        streamingPlatforms: value.streamingPlatforms,
        audioFiles: await from_candid_vec_n65(_uploadFile, _downloadFile, value.audioFiles),
        mediaType: from_candid_MediaType_n68(_uploadFile, _downloadFile, value.mediaType),
        price: value.price,
        youtubeUrl: record_opt_to_undefined(from_candid_opt_n56(_uploadFile, _downloadFile, value.youtubeUrl)),
        images: await from_candid_vec_n70(_uploadFile, _downloadFile, value.images)
    };
}
async function from_candid_record_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    duration: bigint;
    file: _ExternalBlob;
    trackNumber: bigint;
}): Promise<{
    id: string;
    title: string;
    duration: bigint;
    file: ExternalBlob;
    trackNumber: bigint;
}> {
    return {
        id: value.id,
        title: value.title,
        duration: value.duration,
        file: await from_candid_ExternalBlob_n35(_uploadFile, _downloadFile, value.file),
        trackNumber: value.trackNumber
    };
}
async function from_candid_record_n72(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    file: _ExternalBlob;
    isCover: boolean;
}): Promise<{
    id: string;
    file: ExternalBlob;
    isCover: boolean;
}> {
    return {
        id: value.id,
        file: await from_candid_ExternalBlob_n35(_uploadFile, _downloadFile, value.file),
        isCover: value.isCover
    };
}
async function from_candid_record_n75(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    categories: Array<string>;
    order: bigint;
    name: string;
    createdAt: _Time;
    description: string;
    variants: Array<_ProductVariant>;
    isDigital: boolean;
    images: Array<_ExternalBlob>;
}): Promise<{
    id: string;
    categories: Array<string>;
    order: bigint;
    name: string;
    createdAt: Time;
    description: string;
    variants: Array<ProductVariant>;
    isDigital: boolean;
    images: Array<ExternalBlob>;
}> {
    return {
        id: value.id,
        categories: value.categories,
        order: value.order,
        name: value.name,
        createdAt: value.createdAt,
        description: value.description,
        variants: value.variants,
        isDigital: value.isDigital,
        images: await from_candid_vec_n36(_uploadFile, _downloadFile, value.images)
    };
}
async function from_candid_record_n78(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    flyer: [] | [_ExternalBlob];
    status: string;
    title: string;
    venue: string;
    date: _Time;
    ticketLink: string;
    location: string;
}): Promise<{
    id: string;
    flyer?: ExternalBlob;
    status: string;
    title: string;
    venue: string;
    date: Time;
    ticketLink: string;
    location: string;
}> {
    return {
        id: value.id,
        flyer: record_opt_to_undefined(await from_candid_opt_n34(_uploadFile, _downloadFile, value.flyer)),
        status: value.status,
        title: value.title,
        venue: value.venue,
        date: value.date,
        ticketLink: value.ticketLink,
        location: value.location
    };
}
function from_candid_record_n81(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userPrincipal: [] | [string];
    response: string;
}): {
    userPrincipal?: string;
    response: string;
} {
    return {
        userPrincipal: record_opt_to_undefined(from_candid_opt_n56(_uploadFile, _downloadFile, value.userPrincipal)),
        response: value.response
    };
}
function from_candid_record_n84(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _TaskStatus;
    title: string;
    assignedTo: Array<string>;
    description: string;
    deadline: _Time;
}): {
    id: string;
    status: TaskStatus;
    title: string;
    assignedTo: Array<string>;
    description: string;
    deadline: Time;
} {
    return {
        id: value.id,
        status: from_candid_TaskStatus_n85(_uploadFile, _downloadFile, value.status),
        title: value.title,
        assignedTo: value.assignedTo,
        description: value.description,
        deadline: value.deadline
    };
}
function from_candid_variant_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    video: null;
} | {
    image: null;
}): HeroMediaType {
    return "video" in value ? HeroMediaType.video : "image" in value ? HeroMediaType.image : value;
}
function from_candid_variant_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    album: null;
} | {
    video: null;
} | {
    youtube: null;
} | {
    single: null;
}): MediaType {
    return "album" in value ? MediaType.album : "video" in value ? MediaType.video : "youtube" in value ? MediaType.youtube : "single" in value ? MediaType.single : value;
}
function from_candid_variant_n80(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: {
        userPrincipal: [] | [string];
        response: string;
    };
} | {
    failed: {
        error: string;
    };
}): {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
} {
    return "completed" in value ? {
        __kind__: "completed",
        completed: from_candid_record_n81(_uploadFile, _downloadFile, value.completed)
    } : "failed" in value ? {
        __kind__: "failed",
        failed: value.failed
    } : value;
}
function from_candid_variant_n86(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    todo: null;
} | {
    completed: null;
} | {
    inProgress: null;
}): TaskStatus {
    return "todo" in value ? TaskStatus.todo : "completed" in value ? TaskStatus.completed : "inProgress" in value ? TaskStatus.inProgress : value;
}
async function from_candid_vec_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ExternalBlob>): Promise<Array<ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ExternalBlob_n35(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BookingFile>): Promise<Array<BookingFile>> {
    return await Promise.all(value.map(async (x)=>await from_candid_BookingFile_n40(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FileItem>): Promise<Array<FileItem>> {
    return await Promise.all(value.map(async (x)=>await from_candid_FileItem_n58(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MediaItem>): Promise<Array<MediaItem>> {
    return await Promise.all(value.map(async (x)=>await from_candid_MediaItem_n63(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AudioFile>): Promise<Array<AudioFile>> {
    return await Promise.all(value.map(async (x)=>await from_candid_AudioFile_n66(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n70(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ImageFile>): Promise<Array<ImageFile>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ImageFile_n71(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n73(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Product>): Promise<Array<Product>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Product_n74(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n76(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Show>): Promise<Array<Show>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Show_n77(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n82(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Task>): Array<Task> {
    return value.map((x)=>from_candid_Task_n83(_uploadFile, _downloadFile, x));
}
async function to_candid_AboutContent_n87(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AboutContent): Promise<_AboutContent> {
    return await to_candid_record_n88(_uploadFile, _downloadFile, value);
}
async function to_candid_AudioFile_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AudioFile): Promise<_AudioFile> {
    return await to_candid_record_n15(_uploadFile, _downloadFile, value);
}
async function to_candid_BookingConfig_n89(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingConfig): Promise<_BookingConfig> {
    return await to_candid_record_n90(_uploadFile, _downloadFile, value);
}
async function to_candid_BookingFile_n92(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingFile): Promise<_BookingFile> {
    return await to_candid_record_n93(_uploadFile, _downloadFile, value);
}
async function to_candid_DesignConfig_n94(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DesignConfig): Promise<_DesignConfig> {
    return await to_candid_record_n95(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
async function to_candid_FileItem_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FileItem): Promise<_FileItem> {
    return await to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_HeroMediaType_n96(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: HeroMediaType): _HeroMediaType {
    return to_candid_variant_n97(_uploadFile, _downloadFile, value);
}
async function to_candid_HeroVideo_n98(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: HeroVideo): Promise<_HeroVideo> {
    return await to_candid_record_n99(_uploadFile, _downloadFile, value);
}
function to_candid_HomepageConfig_n100(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: HomepageConfig): _HomepageConfig {
    return to_candid_record_n101(_uploadFile, _downloadFile, value);
}
async function to_candid_ImageFile_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ImageFile): Promise<_ImageFile> {
    return await to_candid_record_n20(_uploadFile, _downloadFile, value);
}
async function to_candid_MediaItem_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MediaItem): Promise<_MediaItem> {
    return await to_candid_record_n12(_uploadFile, _downloadFile, value);
}
function to_candid_MediaType_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MediaType): _MediaType {
    return to_candid_variant_n17(_uploadFile, _downloadFile, value);
}
async function to_candid_Product_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Product): Promise<_Product> {
    return await to_candid_record_n22(_uploadFile, _downloadFile, value);
}
async function to_candid_Show_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Show): Promise<_Show> {
    return await to_candid_record_n25(_uploadFile, _downloadFile, value);
}
function to_candid_TaskStatus_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskStatus): _TaskStatus {
    return to_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function to_candid_Task_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Task): _Task {
    return to_candid_record_n27(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation): __ImmutableObjectStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation | null): [] | [__ImmutableObjectStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n101(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    autoUpcomingShows: boolean;
    latestReleaseId?: string;
    upcomingShowIds: Array<string>;
    featuredProductIds: Array<string>;
}): {
    autoUpcomingShows: boolean;
    latestReleaseId: [] | [string];
    upcomingShowIds: Array<string>;
    featuredProductIds: Array<string>;
} {
    return {
        autoUpcomingShows: value.autoUpcomingShows,
        latestReleaseId: value.latestReleaseId ? candid_some(value.latestReleaseId) : candid_none(),
        upcomingShowIds: value.upcomingShowIds,
        featuredProductIds: value.featuredProductIds
    };
}
async function to_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    createdAt: Time;
    description: string;
    streamingPlatforms: Array<StreamingPlatform>;
    audioFiles: Array<AudioFile>;
    mediaType: MediaType;
    price: bigint;
    youtubeUrl?: string;
    images: Array<ImageFile>;
}): Promise<{
    id: string;
    title: string;
    createdAt: _Time;
    description: string;
    streamingPlatforms: Array<_StreamingPlatform>;
    audioFiles: Array<_AudioFile>;
    mediaType: _MediaType;
    price: bigint;
    youtubeUrl: [] | [string];
    images: Array<_ImageFile>;
}> {
    return {
        id: value.id,
        title: value.title,
        createdAt: value.createdAt,
        description: value.description,
        streamingPlatforms: value.streamingPlatforms,
        audioFiles: await to_candid_vec_n13(_uploadFile, _downloadFile, value.audioFiles),
        mediaType: to_candid_MediaType_n16(_uploadFile, _downloadFile, value.mediaType),
        price: value.price,
        youtubeUrl: value.youtubeUrl ? candid_some(value.youtubeUrl) : candid_none(),
        images: await to_candid_vec_n18(_uploadFile, _downloadFile, value.images)
    };
}
async function to_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    duration: bigint;
    file: ExternalBlob;
    trackNumber: bigint;
}): Promise<{
    id: string;
    title: string;
    duration: bigint;
    file: _ExternalBlob;
    trackNumber: bigint;
}> {
    return {
        id: value.id,
        title: value.title,
        duration: value.duration,
        file: await to_candid_ExternalBlob_n10(_uploadFile, _downloadFile, value.file),
        trackNumber: value.trackNumber
    };
}
async function to_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    file: ExternalBlob;
    isCover: boolean;
}): Promise<{
    id: string;
    file: _ExternalBlob;
    isCover: boolean;
}> {
    return {
        id: value.id,
        file: await to_candid_ExternalBlob_n10(_uploadFile, _downloadFile, value.file),
        isCover: value.isCover
    };
}
async function to_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    categories: Array<string>;
    order: bigint;
    name: string;
    createdAt: Time;
    description: string;
    variants: Array<ProductVariant>;
    isDigital: boolean;
    images: Array<ExternalBlob>;
}): Promise<{
    id: string;
    categories: Array<string>;
    order: bigint;
    name: string;
    createdAt: _Time;
    description: string;
    variants: Array<_ProductVariant>;
    isDigital: boolean;
    images: Array<_ExternalBlob>;
}> {
    return {
        id: value.id,
        categories: value.categories,
        order: value.order,
        name: value.name,
        createdAt: value.createdAt,
        description: value.description,
        variants: value.variants,
        isDigital: value.isDigital,
        images: await to_candid_vec_n23(_uploadFile, _downloadFile, value.images)
    };
}
async function to_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    flyer?: ExternalBlob;
    status: string;
    title: string;
    venue: string;
    date: Time;
    ticketLink: string;
    location: string;
}): Promise<{
    id: string;
    flyer: [] | [_ExternalBlob];
    status: string;
    title: string;
    venue: string;
    date: _Time;
    ticketLink: string;
    location: string;
}> {
    return {
        id: value.id,
        flyer: value.flyer ? candid_some(await to_candid_ExternalBlob_n10(_uploadFile, _downloadFile, value.flyer)) : candid_none(),
        status: value.status,
        title: value.title,
        venue: value.venue,
        date: value.date,
        ticketLink: value.ticketLink,
        location: value.location
    };
}
function to_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: TaskStatus;
    title: string;
    assignedTo: Array<string>;
    description: string;
    deadline: Time;
}): {
    id: string;
    status: _TaskStatus;
    title: string;
    assignedTo: Array<string>;
    description: string;
    deadline: _Time;
} {
    return {
        id: value.id,
        status: to_candid_TaskStatus_n28(_uploadFile, _downloadFile, value.status),
        title: value.title,
        assignedTo: value.assignedTo,
        description: value.description,
        deadline: value.deadline
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n88(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bandMembers: Array<string>;
    biography: string;
    pressKit?: ExternalBlob;
    photos: Array<ExternalBlob>;
}): Promise<{
    bandMembers: Array<string>;
    biography: string;
    pressKit: [] | [_ExternalBlob];
    photos: Array<_ExternalBlob>;
}> {
    return {
        bandMembers: value.bandMembers,
        biography: value.biography,
        pressKit: value.pressKit ? candid_some(await to_candid_ExternalBlob_n10(_uploadFile, _downloadFile, value.pressKit)) : candid_none(),
        photos: await to_candid_vec_n23(_uploadFile, _downloadFile, value.photos)
    };
}
async function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    file: ExternalBlob;
    name: string;
    folder: string;
}): Promise<{
    id: string;
    file: _ExternalBlob;
    name: string;
    folder: string;
}> {
    return {
        id: value.id,
        file: await to_candid_ExternalBlob_n10(_uploadFile, _downloadFile, value.file),
        name: value.name,
        folder: value.folder
    };
}
async function to_candid_record_n90(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    files: Array<BookingFile>;
    email: string;
    links: Array<BookingLink>;
    callToAction: string;
}): Promise<{
    files: Array<_BookingFile>;
    email: string;
    links: Array<_BookingLink>;
    callToAction: string;
}> {
    return {
        files: await to_candid_vec_n91(_uploadFile, _downloadFile, value.files),
        email: value.email,
        links: value.links,
        callToAction: value.callToAction
    };
}
async function to_candid_record_n93(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    file: ExternalBlob;
    name: string;
    fileType: string;
}): Promise<{
    id: string;
    file: _ExternalBlob;
    name: string;
    fileType: string;
}> {
    return {
        id: value.id,
        file: await to_candid_ExternalBlob_n10(_uploadFile, _downloadFile, value.file),
        name: value.name,
        fileType: value.fileType
    };
}
async function to_candid_record_n95(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    tagline: string;
    logo?: ExternalBlob;
    heroMediaType: HeroMediaType;
    heroSubtitle: string;
    accentColor: string;
    logoSize: bigint;
    heroImage?: ExternalBlob;
    logoVisibility: LogoVisibility;
    heroTextColor: string;
    heroTextSize: bigint;
    buttonStyle: ButtonStyle;
    quickButtons: Array<QuickButton>;
    heroVideo?: HeroVideo;
    hoverOutlineColor: string;
}): Promise<{
    tagline: string;
    logo: [] | [_ExternalBlob];
    heroMediaType: _HeroMediaType;
    heroSubtitle: string;
    accentColor: string;
    logoSize: bigint;
    heroImage: [] | [_ExternalBlob];
    logoVisibility: _LogoVisibility;
    heroTextColor: string;
    heroTextSize: bigint;
    buttonStyle: _ButtonStyle;
    quickButtons: Array<_QuickButton>;
    heroVideo: [] | [_HeroVideo];
    hoverOutlineColor: string;
}> {
    return {
        tagline: value.tagline,
        logo: value.logo ? candid_some(await to_candid_ExternalBlob_n10(_uploadFile, _downloadFile, value.logo)) : candid_none(),
        heroMediaType: to_candid_HeroMediaType_n96(_uploadFile, _downloadFile, value.heroMediaType),
        heroSubtitle: value.heroSubtitle,
        accentColor: value.accentColor,
        logoSize: value.logoSize,
        heroImage: value.heroImage ? candid_some(await to_candid_ExternalBlob_n10(_uploadFile, _downloadFile, value.heroImage)) : candid_none(),
        logoVisibility: value.logoVisibility,
        heroTextColor: value.heroTextColor,
        heroTextSize: value.heroTextSize,
        buttonStyle: value.buttonStyle,
        quickButtons: value.quickButtons,
        heroVideo: value.heroVideo ? candid_some(await to_candid_HeroVideo_n98(_uploadFile, _downloadFile, value.heroVideo)) : candid_none(),
        hoverOutlineColor: value.hoverOutlineColor
    };
}
async function to_candid_record_n99(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    muted: boolean;
    autoplay: boolean;
    file?: ExternalBlob;
    externalUrl?: string;
    shouldLoop: boolean;
}): Promise<{
    muted: boolean;
    autoplay: boolean;
    file: [] | [_ExternalBlob];
    externalUrl: [] | [string];
    shouldLoop: boolean;
}> {
    return {
        muted: value.muted,
        autoplay: value.autoplay,
        file: value.file ? candid_some(await to_candid_ExternalBlob_n10(_uploadFile, _downloadFile, value.file)) : candid_none(),
        externalUrl: value.externalUrl ? candid_some(value.externalUrl) : candid_none(),
        shouldLoop: value.shouldLoop
    };
}
function to_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MediaType): {
    album: null;
} | {
    video: null;
} | {
    youtube: null;
} | {
    single: null;
} {
    return value == MediaType.album ? {
        album: null
    } : value == MediaType.video ? {
        video: null
    } : value == MediaType.youtube ? {
        youtube: null
    } : value == MediaType.single ? {
        single: null
    } : value;
}
function to_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaskStatus): {
    todo: null;
} | {
    completed: null;
} | {
    inProgress: null;
} {
    return value == TaskStatus.todo ? {
        todo: null
    } : value == TaskStatus.completed ? {
        completed: null
    } : value == TaskStatus.inProgress ? {
        inProgress: null
    } : value;
}
function to_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n97(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: HeroMediaType): {
    video: null;
} | {
    image: null;
} {
    return value == HeroMediaType.video ? {
        video: null
    } : value == HeroMediaType.image ? {
        image: null
    } : value;
}
async function to_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<AudioFile>): Promise<Array<_AudioFile>> {
    return await Promise.all(value.map(async (x)=>await to_candid_AudioFile_n14(_uploadFile, _downloadFile, x)));
}
async function to_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<ImageFile>): Promise<Array<_ImageFile>> {
    return await Promise.all(value.map(async (x)=>await to_candid_ImageFile_n19(_uploadFile, _downloadFile, x)));
}
async function to_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<ExternalBlob>): Promise<Array<_ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await to_candid_ExternalBlob_n10(_uploadFile, _downloadFile, x)));
}
async function to_candid_vec_n91(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<BookingFile>): Promise<Array<_BookingFile>> {
    return await Promise.all(value.map(async (x)=>await to_candid_BookingFile_n92(_uploadFile, _downloadFile, x)));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
